name: test_olliefy
description: Testing env for Olliefy.
publish_to: "none"
version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  app_links: ^6.4.0
  cloud_firestore: ^5.6.7
  country_icons: ^3.0.0
  device_info_plus: ^11.4.0
  ffmpeg_kit_flutter_new: ^1.6.1
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  firebase_dynamic_links: ^6.1.6
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  google_maps_cluster_manager: ^3.1.0
  google_maps_flutter: ^2.12.1
  google_maps_flutter_platform_interface: 2.11.1
  google_sign_in: ^6.3.0
  mask_text_input_formatter: ^2.9.0
  media_kit: ^1.2.0
  media_kit_libs_video_fork: ^0.0.2
  media_kit_video: ^1.3.0
  permission_handler: ^11.3.1
  pin_code_fields: ^8.0.1
  provider: ^6.0.0
  share_plus: ^10.1.4
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  test: ^1.25.15

flutter:
  uses-material-design: true
  assets:
    - ./assets/
    - ./assets/splashscreen/
    - ./assets/icons/
    - ./assets/permissions_page/icons/
    - ./assets/permissions_page/
    - ./assets/profile_page/
    - ./assets/profile_page/favorites_page/
    - ./assets/profile_page/favorites_page/icons/
    - ./assets/profile_page/example_sponsors/
    - ./assets/profile_page/example_posts/
    - ./assets/profile_page/example_stats_items/
    - ./assets/profile_page/example_store_items/
    - ./assets/profile_page/icons/
    - ./assets/profile_page/icons/example_pfp/
    - ./assets/main_app/icons/
    - ./assets/map_page/
    - ./assets/map_page/icons/
    - ./assets/map_page/challenges/
    - ./assets/map_page/posts/
    - ./assets/map_page/spots/
    - ./assets/map_page/markers/
    - ./assets/marketplace_page/
    - ./assets/marketplace_page/example_photos/
    - ./assets/marketplace_page/icons/
    - ./assets/feed_page/icons/
    - ./assets/feed_page/example_videos/
    - ./assets/create_page/
    - ./assets/create_page/icons/
    - ./assets/create_page/icons/post_settings_icons/
