name: test_olliefy
description: Testing env for Olliefy.
publish_to: "none"
version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  country_icons: ^3.0.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  google_maps_cluster_manager: ^3.1.0
  google_maps_flutter: ^2.1.12
  google_maps_flutter_platform_interface: 2.4.3
  mask_text_input_formatter: ^2.9.0
  permission_handler: ^11.3.1
  pin_code_fields: ^8.0.1
  provider: ^6.0.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - ./assets/
    - ./assets/splashscreen/
    - ./assets/icons/
    - ./assets/permissions_page/icons/
    - ./assets/permissions_page/
    - ./assets/profile_page/
    - ./assets/profile_page/favorites_page/
    - ./assets/profile_page/favorites_page/icons/
    - ./assets/profile_page/example_sponsors/
    - ./assets/profile_page/example_posts/
    - ./assets/profile_page/example_stats_items/
    - ./assets/profile_page/example_store_items/
    - ./assets/profile_page/icons/
    - ./assets/profile_page/icons/example_pfp/
    - ./assets/main_app/icons/
    - ./assets/map_page/
    - ./assets/map_page/icons/
    - ./assets/map_page/challenges/
    - ./assets/map_page/posts/
    - ./assets/map_page/spots/
    - ./assets/map_page/markers/
    - ./assets/marketplace_page/
    - ./assets/marketplace_page/example_photos/
    - ./assets/marketplace_page/icons/
    - ./assets/feed_page/icons/
