name: test_olliefy
description: Testing env for Olliefy.
publish_to: "none"
version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  english_words: ^4.0.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  intl_phone_number_input: ^0.7.4
  libphonenumber: ^2.0.2
  permission_handler: ^11.3.1
  provider: ^6.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - ./assets/
    - ./assets/splashscreen/
    - ./assets/icons/
    - ./assets/icons/permissions_page/icons/
    - ./assets/permissions_page/
    - ./assets/profile_page/
    - ./assets/profile_page/icons/
